### ISSUE TITLE
Suffixes

### ISSUE THREAD

**Issue by toxydose** [toxydose/pnwgen#2]
Is it necessary to add an ability to set a list of suffixes? I don`t want to overload the program with useless modules. Suffixes can help you when you will find the half-hidden phone numbers (looks like +0 000 *****00) during information gathering to generating thin-targeted wordlists.

**Comment by knkrth** [comment]
Yes it is. So that it won't generate sequence large number and it will reduce the load by only generating given prefix & suffix. For eg: prefix as 70 & suffix as 10 so that it will generate,

7000000010
 7000000110
 7000000210
  ........................

**Comment by toxydose** [comment]
Thank you for your feedback. I will implement this feature soon.

**Comment by knkrth** [comment]
You are welcome but I'm using this right now http://textmechanic.com/text-tools/numeration-tools/generate-list-numbers/ works well & easy.

**Comment by toxydose** [comment]
i saw the sites like this, but sometimes it is faster to generate the sequence on your PC then generate remotely and then download. Sometimes you don`t have a good Internet connection.

**Comment by knkrth** [comment]
Yes, You are absolutely right.

**Comment by toxydose** [comment]
Added functionality https://github.com/toxydose/pnwgen/commit/f5af60a7acc4a8255d11a661010b62ce6685189d

Just run the program with the suffix in the argument:
e.g
 
    $python3 pnwgen.py 11

also, now you can quickly generate one sequence:

    python3 pnwgen.py [prefix] [suffix]

**Comment by toxydose** [comment]
also, now you can quickly generate one sequence:

    python3 pnwgen.py [prefix] [suffix]

**Comment by knkrth** [comment]
Thank you.
