### ISSUE TITLE
HOW TO??

### ISSUE THREAD

**Issue by unknownghost401** [toxydose/pnwgen#5]
i want to generate numbers starting with 9961 and ending with 8

**Comment by toxydose** [comment]
Hey, sorry for the delayed response.

You should put your prefix (9961) into the prefix.txt file
![image](https://github.com/toxydose/pnwgen/assets/20900400/01dedeb0-9953-4f86-a45a-db49e257cf48)
and run

` ./pnwgen.py 8`
where '8' is your suffix.

![image](https://github.com/toxydose/pnwgen/assets/20900400/b711a8a5-835f-43dc-bf90-f24696cfb924)

here is the output for 7-digits generation:
![image](https://github.com/toxydose/pnwgen/assets/20900400/236f0ed3-8622-4e3e-83c3-27a86704dcda)
