### ISSUE TITLE
Wordlist file size

### ISSUE THREAD

**Issue by sajaltiwari999** [toxydose/pnwgen#6]
Dude i was creating a 10 digit wordlist but the size of wordlist without prefix is going more than 12gb my system crashed what to do ?

**Comment by toxydose** [comment]
Hi, which error do you have? You might have insufficiend disk storage capacity to generate the entire file. In this case you'll receive OSError: [Errno 28] No space left on device error.
The complete 10-digits phone numbers wordlist might have 10 billions of possible combinations and will consume a lot of free disk space.

**Comment by sajaltiwari999** [comment]
Can you please tell me how much space is needed for 10 digit.

**Comment by toxydose** [comment]
I'll generate the 10 digits output and will let you know. Most probably it will be about 300 GB since it is has in 1000 times greater quantity of lines then 7-digits output and 7-digits output weights about 300 MB

PS you should remove the first line in "prefix" file to generate the output without any prefixes, in current condition it generates it including comment in the file. Will update the code later to fix this issue.

**Comment by sajaltiwari999** [comment]
Oo ya thanks after I removes texy from prefix the size of worlist decreased alot. And also plzz tell me the size for 10 digit. As I am using Kali Linux in VM Ware and I have only alloted 2GB to VM Ware 😂

**Comment by toxydose** [comment]
Thank you for the update. I've updated the code to ignore comments in the prefix file. Please feel free to test it.
There are some hints which will allow you to validate if the wordlist was generated correctly without opening it in the text editors:

```
wc -l wordlist.txt    #showing the number of lines in the document
tail wordlist.txt    #showing last lines of the file
less wordlist.txt    #showing first lines of the file
```

I'll regenerate the 10 digits file with the updated code and will let you know what will be the final file size. Will update warning in readme accordingly. Please let me know if you find any bugs or have any questions.

**Comment by sajaltiwari999** [comment]
Thanks for adding such features. Actually I was facing an issue to open wordfile.txt because notepad was no opening such large file I used VS Code but it also started lagging. Also waiting for the file size of 10 digit hope you will tell me soon 😊.... ❤️ from 🇮🇳

**Comment by toxydose** [comment]
The file is 111 GB :) Let me know if I can close this ticket : )
